- name: Download helm
  get_url: 
    url: "{{ helm }}" 
    dest: /opt/kubernetes/get_helm.sh
    mode: 0775
  ignore_errors: true 
  register: download

- name: Instalando Helm
  command: /opt/kubernetes/get_helm.sh
  when: download
  register: install_helm
  become_user: "{{ linux_user }}"

- name: Variavel var
  debug:
    var: install_helm